name = "waldensrevisited"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[observability]
enabled = true
head_sampling_rate = 1

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[vars]
GOOGLE_CLIENT_ID = "865105554486-uu5ilnjk0oshjlu4iib4aidaptii476r.apps.googleusercontent.com"
ADMIN_EMAILS = "admin@waldensrevisited.org"

[[d1_databases]]
binding = "DB"
database_name = "waldensrevisited-db"
database_id = "566ef81b-4b57-47f7-bc41-20c876df8743"

[[kv_namespaces]]
binding = "SESSIONS"
id = "daa6aa2a8b2146f995f773106d070a8f"

# [[r2_buckets]]
# binding = "UPLOADS"
# bucket_name = "waldensrevisited-uploads"

[env.beta]
name = "waldensrevisited-beta"
